version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      # "cypress" is the name of the imported orb
      - cypress/install:
          name: Install everything

      # "run" is the name of the job defined in Cypress orb
      - cypress/run:
          name: Sanity Cypress tests
          requires:
            - Install everything
          parallel: true
          parallelism: 1
          start: npm start
          wait-on: 'http://localhost:8080'
          no-workspace: true
          spec: 'cypress/integration/spec3.js'
          record: true
          tags: CircleCI
          group: '1. Sanity'

      - cypress/run:
          name: All Cypress tests
          requires:
            - Sanity Cypress tests
          parallel: true
          parallelism: 3
          start: npm start
          wait-on: 'http://localhost:8080'
          no-workspace: true
          record: true
          tags: CircleCI
          group: '1. All tests'
