version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      # "cypress" is the name of the imported orb
      - cypress/install:
          name: Install everything

      # "run" is the name of the job defined in Cypress orb
      - cypress/run:
          name: Run Cypress tests
          requires:
            - Install everything
          install-command: echo 'Everything was already installed'
          start: npm start
          wait-on: 'http://localhost:8080'
          no-workspace: true
          record: true
          tags: CircleCI
          group: '1. All tests'
